config/routes.rb
Dvdapp::Application.routes.draw do
  resources :directors

  resources :genres

  resources :dvds

  root :controller => "dvds", :action => "index"

end

app/models/director.rb
# == Schema Information
#
# Table name: directors
#
#  id         :integer          not null, primary key
#  fname      :string(255)
#  lname      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Director < ActiveRecord::Base
  attr_accessible :fname, :lname
  has_many :dvds
  
  validates :fname, :presence => true
  validates :fname, :length => { :maximum => 255 }
  
  validates :lname, :presence => true
  validates :lname, :length => { :maximum => 255 }
  
  def full_name
    "#{lname}. #{fname}"
  end


end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @directors }
    end
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
    @director = Director.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @director }
    end
  end

  # GET /directors/new
  # GET /directors/new.json
  def new
    @director = Director.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @director }
    end
  end

  # GET /directors/1/edit
  def edit
    @director = Director.find(params[:id])
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(params[:director])

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render json: @director, status: :created, location: @director }
      else
        format.html { render action: "new" }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /directors/1
  # PUT /directors/1.json
  def update
    @director = Director.find(params[:id])

    respond_to do |format|
      if @director.update_attributes(params[:director])
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director = Director.find(params[:id])
    @director.destroy

    respond_to do |format|
      format.html { redirect_to directors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<%= form_for(@director) do |f| %>
  <% if @director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
      <% @director.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "First name" %><br />
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label "Last Name" %><br />
    <%= f.text_field :lname %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<% provide(:title, @director.full_name) %>

<h1>Editing director</h1>

<%= render 'form' %>

<%= link_to 'Show', @director %> |
<%= link_to 'Back', directors_path %>

app/views/directors/index.html.erb
<% provide(:title, "Listing Directors") %>

<h1>Listing directors</h1>

<table class="table table-bordered table-condensed table-striped">
  <thead>	
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @directors.each do |director| %>
    <tr>
      <td><%= director.fname %></td>
      <td><%= director.lname %></td>
      <td><%= link_to 'Show', director %></td>
      <td><%= link_to 'Edit', edit_director_path(director) %></td>
      <td><%= link_to 'Destroy', director, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Director', new_director_path %>

app/views/directors/new.html.erb
<% provide(:title, "New Director") %>

<h1>New director</h1>

<%= render 'form' %>

<%= link_to 'Back', directors_path %>

app/views/directors/show.html.erb
<% provide(:title, @director.full_name) %>

<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @director.fname %>
</p>

<p>
  <b>Last name:</b>
  <%= @director.lname %>
</p>


<%= link_to 'Edit', edit_director_path(@director) %> |
<%= link_to 'Back', directors_path %>