config/routes.rb
Dvdapp::Application.routes.draw do
  resources :directors

  resources :genres

  resources :dvds

  root :controller => "dvds", :action => "index"

end

app/models/dvd.rb
# == Schema Information
#
# Table name: dvds
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  release     :integer
#  genre_id    :integer
#  director_id :integer
#  notes       :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Dvd < ActiveRecord::Base
  attr_accessible :title, :release, :genre_id, :director_id, :notes, :url

  belongs_to :genre
  belongs_to :director

  #delegate :genre_id, :to=>:genre, :prefix=>true, :allow_nil=>true

  validates :title, :presence => true
  validates :title, :length => {:maximum => 255}
  validates :notes, :length => {:maximum => 255} 	

  validates :release, :numericality => { :greater_than_or_equal_to => 1900 }
end

app/controllers/dvds_controller.rb
class DvdsController < ApplicationController
  # GET /dvds
  # GET /dvds.json
  def index
    @dvds = Dvd.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dvds }
    end
  end

  # GET /dvds/1
  # GET /dvds/1.json
  def show
    @dvd = Dvd.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dvd }
    end
  end

  # GET /dvds/new
  # GET /dvds/new.json
  def new
    
    @genres = Genre.all.sort_by(&:name)
    @directors = Director.order("lower(lname), lower(fname) ASC")
    
    @dvd = Dvd.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dvd }
    end
  end

  # GET /dvds/1/edit
  def edit
    
    @genres = Genre.all.sort_by(&:name)
    @directors = Director.order("lower(lname), lower(fname) ASC")
	  
    @dvd = Dvd.find(params[:id])
  end

  # POST /dvds
  # POST /dvds.json
  def create
    
    @genres = Genre.all.sort_by(&:name)
    @directors = Director.order("lower(lname), lower(fname) ASC")
	  
    @dvd = Dvd.new(params[:dvd])

    respond_to do |format|
      if @dvd.save
        format.html { redirect_to @dvd, notice: 'Dvd was successfully created.' }
        format.json { render json: @dvd, status: :created, location: @dvd }
      else
        format.html { render action: "new" }
        format.json { render json: @dvd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dvds/1
  # PUT /dvds/1.json
  def update
    @dvd = Dvd.find(params[:id])

    respond_to do |format|
      if @dvd.update_attributes(params[:dvd])
        format.html { redirect_to @dvd, notice: 'Dvd was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dvd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dvds/1
  # DELETE /dvds/1.json
  def destroy
    @dvd = Dvd.find(params[:id])
    @dvd.destroy

    respond_to do |format|
      format.html { redirect_to dvds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dvds_helper.rb
module DvdsHelper
  def include_boxcover
    unless @dvd.url.blank?
      include_image(@dvd.url, @dvd.title, "center")
    end
  end 
end

app/views/dvds/_form.html.erb
<%= form_for(@dvd, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @dvd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dvd.errors.count, "error") %> prohibited this dvd from being saved:</h2>

      <ul>
      <% @dvd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      
    </div>
  <% end %>
  <fieldset>
    <div class="control-group">
      <%= f.label :title, :class => "control-label"%>
      <div class="controls">
	      <%= f.text_field :title, :class => "input-xlarge" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :release, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :release, :class => "input-small" %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :genre, :class => "control-label" %>
      <div class="controls">
        <%= collection_select(:dvd, :genre_id, @genres, :id, :name, :prompt => true) %>
      </div>
    </div>
  <div class="control-group">
    <%= f.label :director, :class => "control-label" %>
    <div class="controls">
      <%= collection_select(:dvd, :director_id, @directors, :id, :full_name, :prompt => true) %>
    </div>
  </div>  
  <div class="control-group">
    <%= f.label :notes,:class => "control-label" %>
    <div class="controls">
	    <%= f.text_area :notes, :class => "input-xlarge", :size => "60x12" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :url, :class => "input-xlarge" %>
      <span class="help-block">URL of a boxcover image</span> 
    </div>
  </div>
  <div class="form-actions">
	  
    <%= f.submit class: "btn btn-large btn-primary" %>
  </div>
  </fieldset>
<% end %>

app/views/dvds/edit.html.erb
<% provide(:title, @dvd.title) %>

<h1>Editing dvd</h1>

<%= render 'form' %>

<%= link_to 'Show', @dvd %> |
<%= link_to 'Back', dvds_path %>

app/views/dvds/index.html.erb
<% provide(:title, "Listing DVDs") %>
<h1>Listing dvds</h1>

<table class="table table-bordered table-condensed table-striped">
  <thead>
    <tr>	  
      <th>Title</th>
      <th>Release</th>
      <th>Genre</th>
      <th>Director</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @dvds.each do |dvd| %>
    <tr>
      <td><%= dvd.title %></td>
      <td><%= dvd.release %></td>
      <td><%= dvd.try(:genre).try(:name) %></td>
      <td><%= dvd.try(:director).try(:full_name) %></td>
      <td><%= link_to 'Show', dvd %></td>
      <td><%= link_to 'Edit', edit_dvd_path(dvd) %></td>
      <td><%= link_to 'Destroy', dvd, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Dvd', new_dvd_path %>

app/views/dvds/new.html.erb
<% provide(:title, "New DVD") %>

<h1>New dvd</h1>

<%= render 'form' %>

<%= link_to 'Back', dvds_path %>

app/views/dvds/show.html.erb
<% provide(:title, @dvd.title) %>
<p id="notice"><%= notice %></p>

<h1> 
  <%= @dvd.title %>
</h1>
<div id="box_cover">
  <%= include_boxcover %>
</div>
  <div class="row-fluid">
    <div class="span1"><b>Title:</b></div>
    <div class="span11">  <%= @dvd.title %> </div>
  </div>

  <div class="row-fluid">
    <div class="span1"><b>Release:</b></div>
    <div class="span11"><%= @dvd.release %></div>
  </div>

  <div class="row-fluid">
    <div class="span1"><b>Genre:</b></div>
    <div class="span11"><%= @dvd.try(:genre).try(:name) %></div>
  </div>  
		    		    
  <div class="row-fluid">
    <div class="span1"><b>Director:</b></div>
    <div class="span11"><%= @dvd.try(:director).try(:full_name) %></div>
  </div>

  <div class="row-fluid">
    <div class="span1"><b>Notes:</b></div>
    <div class="span11"><%= @dvd.notes %></div>
  </div>
<%= link_to 'Edit', edit_dvd_path(@dvd) %> |
<%= link_to 'Back', dvds_path %>